### ISSUE TITLE
Syntax for suggested merging of data assets

### ISSUE THREAD

**Issue by rabernat** [NCAR/esm-collection-spec#6]
It should always be an option for an application to open the data assets (the rows of the CSV file) one-by-one. However, as discussed in the [design document](https://hackmd.io/@Tk4Zdl52TT6lvxneSz_IfA/BkHKYn-HS), we also may want to "suggest" how the assets can be merged / aggregated.

@andersy005 original had this in yaml.
```yaml
# define the set of attributes for which common values indicate
# datasets that can be merged or concatenated. `intake-esm` applies
# `df.groupby(col_compatible_dset_attrs)` to determine the unique groups
col_compatible_dset_attrs: 
     - institution_id
     - source_id
     - experiment_id
     - table_id
     - grid_label

# define a set of new dimensions across which to 
# concatenate and construct a return dataset.
col_concat_newdim_attrs: 
     - member_id

# define a set of collection attributes across which to 
# merge returned datasets
col_merge_attrs: 
     - variable_id
```

I'm not sure exactly how the new syntax would look. We should try to leverage the vocabulary from [ncml](https://www.unidata.ucar.edu/software/netcdf-java/current/ncml/Aggregation.html) rather than inventing something new.

This issue is also discussed in https://github.com/pydata/xarray/issues/2697.
